### ISSUE TITLE
/docs/* routes in dev aren't served

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/radium-docs#13]
Visiting a /docs/* link directly, or refreshing the page while on that route breaks the routing. Works fine though clicking on links.

**Comment by paulathevalley** [comment]
@kylecesmat Is this resolved with the `--history-api-fallback` flag?

**Comment by kylecesmat** [comment]
@paulathevalley no, it's a very weird thing thats happening and I can't figure out why yet

**Comment by paulathevalley** [comment]
I looked into it. Refreshing `localhost:3000/docs/guide` looks for the JS bundle at `localhost:3000/docs/main.js` but it's actually at `localhost:3000/main.js` 

...so, the `<base href="/" />` in `index.html` fixes it. Not sure if there’s another option!
