### ISSUE TITLE
SSR Loading Breaks Header

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/radium-docs#25]
While the site is loading, the initial render doesn't have certain styles that define the layout once the page is loaded.

Loading:
![screen shot 2016-07-22 at 1 57 42 pm](https://cloud.githubusercontent.com/assets/1633837/17071123/74628552-5014-11e6-9dbe-2da2e64fc5bc.png)

Loaded:
![screen shot 2016-07-22 at 2 00 21 pm](https://cloud.githubusercontent.com/assets/1633837/17071155/aafbb0d4-5014-11e6-9aa8-dcc2acb3578f.png)

**Comment by paulathevalley** [comment]
This happens on the victory docs, too!
