### ISSUE TITLE
CONTRIBUTING.md relative links are broken

### ISSUE THREAD

**Issue by bmathews** [FormidableLabs/radium-docs#26]
on `/docs` and `/docs/getting-started`

e.g.,
![image](https://cloud.githubusercontent.com/assets/848347/17220115/fce82b74-54a2-11e6-93ab-736f8dac89b2.png)

**Comment by kylecesmat** [comment]
Fixed by https://github.com/FormidableLabs/radium/commit/0dd3259ea120e624ca22059436e064c31b60a37c

Will be fixed in next release
