### ISSUE TITLE
Separate views for home & docs

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/radium-docs#7]
Following suit of some of our other doc-sites, we should build seperate routes and views for docs & home. This is the general plan I think:

Home - Content includes getting started, and a playground to interact with a style object. Something similar to the current Radium site. I think we should side with less code/content, and more directional copy/examples and offering links to associated docs pages. *Are we okay with this content residing within radium-docs, separate from the parent repository?*

Docs - Perhaps a simple sidebar with links to these various documentation files:
- Using Radium (main README.md file - I think this is a good "default" page, it acts as a "getting started" document)
- API Docs
- FAQ
- Guides
- Comparison

Open to discussion
cc @paulathevalley @alexlande

**Comment by alexlande** [comment]
> Are we okay with this content residing within radium-docs, separate from the parent repository?

Ideally, I'd like to keep docs content in the main radium repo if at all possible. That's easier for users looking for it, and easier for contributors.

**Comment by kylecesmat** [comment]
Merged in #8
